export const SUGGESTION_LIMIT = 120;
export const MATCH_REVIEW_THRESHOLD = 0.58;

export const STRONG_MODEL_CATEGORIES = new Set([
  "Accesorios de extraccion",
  "Bandejas y ceniceros",
  "Bongs",
  "Encendedores y sopletes",
  "Moledores",
  "Pipas",
  "Repuestos para bongs y vaporizadores",
  "Vaporizadores herbales",
]);

export const KNOWN_BRAND_PHRASES = [
  "airis",
  "aku",
  "american helix",
  "actitube",
  "arizer",
  "blazy susan",
  "blazer",
  "bonglab",
  "bukket",
  "bulldog",
  "c-thru",
  "cabo",
  "calvo",
  "cookies",
  "clipper",
  "dark horse",
  "dynavap",
  "elements",
  "dream high",
  "eyce",
  "formula secreta",
  "futurola",
  "galaxy",
  "gizeh",
  "grav",
  "g-rollz",
  "hemper",
  "hightrip",
  "honeypuff",
  "ignite",
  "kema",
  "lion rolling circus",
  "mj arsenal",
  "ocb",
  "octave",
  "ozeta",
  "pax",
  "piecemaker",
  "pulsar",
  "raw",
  "ronson",
  "special blue",
  "santa cruz shredder",
  "santa cruz",
  "slx",
  "stundenglass",
  "soulblime",
  "smokers choice",
  "storz bickel",
  "strabe glass",
  "syfy",
  "the bulldog",
  "top smoke",
  "vibes",
  "waxmaid",
  // OJO: no crear alias fenix->weecke; Bonglab tambien vende bongs "Fire Fenix".
  "weecke",
  "xvape",
  "yocan",
  "zengaz",
  "zippo",
  "puffco",
  "davinci",
  "da vinci",
  "marley natural",
  "focus v",
  "higher standards",
  "blunt wrap",
  "kush hemp",
  "ryot",
];

// Fuente unica de aliases de marca (frase -> brandKey). La comparten el
// scraper, el backfill y el matching; el alias gb-the-green-brand se maneja
// aparte en cada script porque es un fallback de ultima prioridad.
export const BRAND_ALIASES = new Map<string, string>([
  ["the bulldog amsterdam", "the-bulldog"],
  ["the bulldog", "the-bulldog"],
  ["bulldog", "the-bulldog"],
  ["calvo glass", "calvo"],
  ["bong lab", "bonglab"],
  ["piece maker", "piecemaker"],
  ["pmg", "piecemaker"],
  ["easy valve", "storz-bickel"],
  ["solid valve", "storz-bickel"],
  ["volcano", "storz-bickel"],
  ["mighty", "storz-bickel"],
  ["crafty", "storz-bickel"],
  ["lightning grinder", "galaxy"],
  ["papelillo celulosa transparente", "c-thru"],
]);

export const KNOWN_BRANDS = [
  "raw",
  "ocb",
  "bonglab",
  "galaxy",
  "gizeh",
  "zippo",
  "calvo",
  "clipper",
  "pax",
  "ozeta",
  "futurola",
  "blazy susan",
  "storz bickel",
  "storz & bickel",
  "dynavap",
  "davinci",
  "slx",
  "hemper",
  "the bulldog",
  "cabo",
  "piecemaker",
  "american helix",
  "top smoke",
  "zengaz",
  "blunt wrap",
  "kush hemp",
  "formula secreta",
  "focus v",
  "lion rolling circus",
  "airis",
  "mr pipe cleaner",
  "vibes",
  "kush",
  "aku",
  "bukket",
  "c-thru",
  "cookies",
  "dark horse",
  "honeypuff",
  "kema",
  "special blue",
  "syfy",
  "waxmaid",
  "weecke",
  "yocan",
];

export const MATERIAL_TOKENS = new Set([
  "acrilico",
  "aluminio",
  "aluminum",
  "borosilicato",
  "borosilicate",
  "ceramic",
  "ceramics",
  "ceramica",
  "ceramico",
  "carton",
  "cartonico",
  "cardboard",
  "carbon",
  "cuarzo",
  "glass",
  "madera",
  "metal",
  "metalica",
  "metalico",
  "plastic",
  "plastico",
  "pyrex",
  "quartz",
  "silicona",
  "silicone",
  "vidrio",
]);

export const MATERIAL_KEYS = new Map([
  ["aluminio", "metal"],
  ["aluminum", "metal"],
  ["borosilicato", "glass"],
  ["borosilicate", "glass"],
  ["ceramic", "ceramic"],
  ["ceramics", "ceramic"],
  ["ceramica", "ceramic"],
  ["ceramico", "ceramic"],
  ["carton", "paper"],
  ["cartonico", "paper"],
  ["cardboard", "paper"],
  ["carbon", "carbon"],
  ["cuarzo", "quartz"],
  ["metalica", "metal"],
  ["metalico", "metal"],
  ["pyrex", "glass"],
  ["quartz", "quartz"],
  ["silicona", "silicone"],
  ["silicone", "silicone"],
  ["vidrio", "glass"],
  ["plastic", "plastic"],
  ["plastico", "plastic"],
]);

export const DESCRIPTOR_TOKENS = new Set([
  "amarillo",
  "azul",
  "black",
  "blanco",
  "blue",
  "classic",
  "clasica",
  "clasico",
  "clear",
  "dorado",
  "grande",
  "green",
  "mediana",
  "mediano",
  "mini",
  "negra",
  "negro",
  "pequena",
  "pequeno",
  "red",
  "rojo",
  "transparente",
  "verde",
  "white",
]);

export const DESCRIPTOR_KEYS = new Map([
  ["black", "black"],
  ["negra", "black"],
  ["negro", "black"],
  ["blue", "blue"],
  ["azul", "blue"],
  ["clear", "clear"],
  ["transparente", "clear"],
  ["green", "green"],
  ["verde", "green"],
  ["red", "red"],
  ["rojo", "red"],
  ["white", "white"],
  ["blanco", "white"],
  ["clasica", "classic"],
  ["clasico", "classic"],
  ["mediano", "mediana"],
  ["pequena", "mini"],
  ["pequeno", "mini"],
]);

export const COLOR_GROUPS = [
  ["amarillo"],
  ["azul", "blue", "celeste"],
  ["black", "negra", "negro"],
  ["blanco", "white"],
  ["clear", "transparente"],
  ["dorado", "gold"],
  ["green", "verde"],
  ["morado", "purple"],
  ["pink", "rosada", "rosado", "rose"],
  ["plateado", "silver"],
  ["red", "rojo"],
];

export const COLOR_KEYS = new Map<string, string>(
  COLOR_GROUPS.flatMap((group) => group.map((token) => [token, group[0]] as const)),
);

export const SCALE_GROUPS = [
  ["mini", "pequena", "pequeno", "small"],
  ["mediana", "mediano", "medium"],
  ["grande", "large"],
];

export const SCALE_KEYS = new Map<string, string>(
  SCALE_GROUPS.flatMap((group) => group.map((token) => [token, group[0]] as const)),
);

export const HARD_MODEL_TOKENS = new Set([
  "diamond",
  "giratorio",
  "herb",
  "lightning",
  "lite",
  "mars",
  "model",
  "pocket",
  "pro",
  "quartz",
  "saver",
  "square",
  "swing",
]);

export const BRAND_SIZE_MATCH_CATEGORIES = new Set([
  "accesorios de extraccion",
  "conos y blunts",
  "contenedores y estuches",
  "encendedores y sopletes",
  "filtros y boquillas",
  "limpieza",
  "papelillos",
  "repuestos para bongs y vaporizadores",
]);

export const BRAND_MODEL_MATCH_CATEGORIES = new Set([
  "accesorios de extraccion",
  "bandejas y ceniceros",
  "bongs",
  "contenedores y estuches",
  "encendedores y sopletes",
  "filtros y boquillas",
  "limpieza",
  "moledores",
  "papelillos",
  "pipas",
  "repuestos para bongs y vaporizadores",
  "vaporizadores herbales",
]);

export const GENERIC_TOKENS = new Set([
  "a",
  "accesorio",
  "accesorios",
  "aleatoria",
  "aleatorio",
  "aprox",
  "aproximado",
  "articulo",
  "articulos",
  "activado",
  "activo",
  "bandeja",
  "bandejas",
  "bong",
  "bongs",
  "boquilla",
  "boquillas",
  "brand",
  "blanqueado",
  "blanqueados",
  "blanquear",
  "blanqueamiento",
  "cachimba",
  "cachimbas",
  "cannabis",
  "chile",
  "cl",
  "cierre",
  "cm",
  "color",
  "colorante",
  "colorantes",
  "colores",
  "compacto",
  "compartidor",
  "compartimento",
  "compartimentos",
  "con",
  "de",
  "del",
  "duradero",
  "diseno",
  "el",
  "eleccion",
  "en",
  "encendedor",
  "encendedores",
  "enrolar",
  "extra",
  "extrafino",
  "extrafinos",
  "fine",
  "fino",
  "finos",
  "fumar",
  "fumador",
  "fumadores",
  "filtro",
  "filtros",
  "generico",
  "gb",
  "grinder",
  "growbarato",
  "hoja",
  "hojas",
  "html",
  "http",
  "https",
  "king",
  "la",
  "las",
  "liar",
  "los",
  "m",
  "marihuana",
  "metalico",
  "metalica",
  "model",
  "modelo",
  "ml",
  "mm",
  "moledor",
  "moledores",
  "natural",
  "neodimio",
  "new",
  "origen",
  "para",
  "parafernalia",
  "papel",
  "papeleria",
  "papeles",
  "papelillo",
  "papelillos",
  "parte",
  "partes",
  "pipa",
  "pipas",
  "pieza",
  "piezas",
  "piso",
  "pisos",
  "piranha",
  "producto",
  "productos",
  "recargable",
  "resistente",
  "shop",
  "sin",
  "size",
  "slim",
  "smokeshop",
  "soplete",
  "sopletes",
  "the",
  "tienda",
  "tamiz",
  "tip",
  "tips",
  "tray",
  "ultra",
  "ultrafino",
  "ultrafinos",
  "u",
  "ud",
  "uds",
  "und",
  "unidad",
  "unidades",
  "usar",
  "uso",
  "variado",
  "variados",
  "variedad",
  "variedades",
  "vaporizador",
  "vaporizadores",
  "vegano",
  "www",
  "y",
]);

export const MODEL_TOKENS = new Set([
  "45",
  "90",
  "artesano",
  "automatico",
  "bamboo",
  "beaker",
  "brazilian",
  "bucket",
  "classic",
  "clasica",
  "clasico",
  "coil",
  "crafty",
  "diamond",
  "emerald",
  "flight",
  "flat",
  "full",
  "girl",
  "honeycomb",
  "inline",
  "king-size",
  "macho",
  "mighty",
  "organic",
  "percolator",
  "prepare",
  "pro",
  "regular",
  "rig",
  "slurper",
  "straight",
  "tube",
  "venty",
  "weld",
  "herb",
  "saver",
  "mini",
  "mars",
  "swing",
  "lite",
  "ecologico",
  "eco",
  "tarjeta",
  "card",
  "acrilico",
  "acrylic",
  "llavero",
  "keychain",
  "ceramics",
  "quartz",
  "lightning",
]);

export const KNOWN_MODEL_PHRASES = [
  "baby cake",
  "beaker plus",
  "beaker tree perc",
  "big blow",
  "big eye",
  "bongbastic",
  "bubbler kush",
  "color cube",
  "classic ice",
  "cristal mini",
  "diamond",
  "doble cuerno",
  "doble inline",
  "dream rig",
  "fat candy",
  "glycerin green avalanche",
  "glycerin thicc",
  "glycerin the yeti",
  "handy rig",
  "headshot",
  "heavy bubbler",
  "heavy trash",
  "honey drips",
  "honey waffle",
  "jelly drop",
  "jelly fish",
  "k104 moon",
  "k276",
  "k306",
  "k41",
  "k47 medusa",
  "k99 octopus",
  "km3 clear",
  "km8 viper",
  "little buchner",
  "mad professor",
  "mercurial kh1",
  "mercurial smokey",
  "mini beaker",
  "nevis rig",
  "new pro",
  "pocket bell",
  "prisma",
  "pro model",
  "r2 bonglab",
  "r3 mini",
  "rick sanchez",
  "roller coaster",
  "shiva blue",
  "space oddity",
  "space opera",
  "straight tube",
  "the sheikh",
  "the trash",
  "tiny bell",
  "unikorn",
  "water splash",
];

export const EXCLUSIVE_MODEL_GROUPS = [
  ["45", "90"],
  ["brazilian", "girl", "classic", "emerald", "prepare"],
  ["bucket", "slurper", "honeycomb", "flat", "regular"],
  ["crafty", "mighty", "venty"],
];

export const EXCLUSIVE_OPTION_TOKENS = new Set([
  "boquilla",
  "boquillas",
  "filtro",
  "filtros",
  "insert",
  "kit",
  "king-size",
  "pre-rolled",
  "pre-rolado",
  "pre-rolados",
  "roll",
  "rollo",
  "sabanas",
  "slim",
  "tip",
  "tips",
]);

export const DESCRIPTOR_WILDCARD_TOKENS = new Set(["color", "colores"]);

export const OPTIONAL_DESCRIPTOR_TOKENS = new Set([
  "amarillo",
  "animal",
  "azul",
  "black",
  "blanco",
  "blue",
  "celeste",
  "clear",
  "color",
  "colores",
  "dorado",
  "gold",
  "green",
  "morado",
  "natural",
  "negra",
  "negro",
  "pink",
  "plateado",
  "print",
  "purple",
  "red",
  "rojo",
  "rose",
  "silver",
  "transparente",
  "verde",
  "white",
]);

export const EXCLUSIVE_DESCRIPTOR_GROUPS = [
  ["amarillo"],
  ["animal"],
  ["azul", "blue", "celeste"],
  ["black", "negra", "negro"],
  ["blanco", "white"],
  ["clear", "transparente"],
  ["dorado", "gold"],
  ["green", "verde"],
  ["morado", "purple"],
  ["pink", "rose"],
  ["plateado", "silver"],
  ["print"],
  ["red", "rojo"],
];

export const EXCLUSIVE_DESCRIPTOR_KEYS = new Map<string, string>(
  EXCLUSIVE_DESCRIPTOR_GROUPS.flatMap((group) => group.map((token) => [token, group[0]] as const)),
);
