export const SUGGESTION_LIMIT = 120;
export const MATCH_REVIEW_THRESHOLD = 0.58;

export const STRONG_MODEL_CATEGORIES = new Set([
  "Accesorios de extraccion",
  "Bandejas y ceniceros",
  "Bongs",
  "Encendedores y sopletes",
  "Moledores",
  "Pipas",
  "Repuestos para bongs y vaporizadores",
  "Vaporizadores herbales",
]);

export const KNOWN_BRAND_PHRASES = [
  "airis",
  "aku",
  "american helix",
  // r53: marcas que Friendly Grow trae y el catalogo no conocia. Van como FRASE
  // completa a proposito: "phoenix" solo colisiona con la "Pipa Pyrex Phoenix 71"
  // de Top Smoke, y "gorilla" con otros modelos. Descartadas en la misma revision:
  // "tornasol" (es un acabado; lo usan Gizeh, Clipper, The Bulldog y Cobra) y
  // "vaporesso" (pod kits de e-liquido, fuera del alcance del catalogo).
  "baked bunny",
  "gorilla rolling star",
  "phoenix star",
  // r68: 7 ofertas de Friendly Grow (bateria 510 Dazzleaf Alien en 6 colores +
  // la Spaceman). Estaba sin registrar, asi que 6 quedaban SIN marca y la
  // Spaceman caia en "galaxy" porque la tienda declara brand=GALAXY en un
  // producto que su propio titulo llama Dazzleaf. Dentro de alcance: es una
  // bateria 510 para cartuchos, no un pod kit de e-liquido.
  "dazzleaf",
  // r74: la "TOQI Blunt Box" de Fumetas caia en "boveda" SIN que su titulo, su
  // URL ni su campo `brand` dijeran boveda -- los tres dicen TOQI. Entraba por el
  // FALLBACK POR DESCRIPTION, que solo se usa cuando ninguna marca conocida
  // calza: al no estar registrada, el humidificador se llevaba la marca de los
  // sachets que su propio texto menciona. Registrarla cierra el fallback.
  "toqi",
  "actitube",
  "arizer",
  "blazy susan",
  "blazer",
  "boveda",
  "bonglab",
  "bukket",
  "bulldog",
  "c-thru",
  "cabo",
  "airistech",
  "calvo",
  "cookies",
  "clipper",
  "dark horse",
  "dime bags",
  "dynavap",
  "elements",
  "dream high",
  "eyce",
  "formula secreta",
  "fume",
  "futurola",
  "galaxy",
  "gizeh",
  "grav",
  "g-rollz",
  "hemper",
  "hightrip",
  "honeypuff",
  "ignite",
  "integra boost",
  "kasvi",
  "kema",
  "kleaner",
  "lady hornet",
  "life pod",
  "lion rolling circus",
  "mj arsenal",
  "naar",
  "nasty",
  "ocb",
  "octave",
  "oxbar",
  "oxva",
  "ozeta",
  "pax",
  "piecemaker",
  "prima klima",
  "presize",
  "pulsar",
  "raw",
  "ronson",
  "smoking",
  "smokus focus",
  "sploofy",
  "g pen",
  "special blue",
  "santa cruz shredder",
  "santa cruz",
  "slx",
  "stundenglass",
  "soulblime",
  "smokers choice",
  "storz bickel",
  "strabe glass",
  "syfy",
  "the bulldog",
  "top smoke",
  "truweigh",
  "vibes",
  "waxmaid",
  // OJO: no crear alias fenix->weecke; Bonglab tambien vende bongs "Fire Fenix".
  "weecke",
  "xvape",
  "yocan",
  "zengaz",
  "zippo",
  "puffco",
  "davinci",
  "da vinci",
  "marley natural",
  "focus v",
  "higher standards",
  "blunt wrap",
  "kush hemp",
  "ryot",
  // Marcas que el catalogo ya vende pero no reconocia. Sin ellas el scraper ni
  // siquiera visitaba sus paginas: su slug no trae palabra de tipo (ej.
  // /atmos-micropal, /cali-crusher-slick-mediano) y el descubrimiento exige
  // keyword O marca conocida (diagnostico de cobertura, 2026-07-21).
  "boveda",
  "truweigh",
  "cali crusher",
  "boundless",
  "atmos",
  "magic flight",
  "shine",
  "khemo",
  "pypetek",
  "brass knuckles",
  "kannastor",
  "kingpalm",
  "cvault",
  "empire",
];

// Fuente unica de aliases de marca (frase -> brandKey). La comparten el
// scraper, el backfill y el matching; el alias gb-the-green-brand se maneja
// aparte en cada script porque es un fallback de ultima prioridad.
export const BRAND_ALIASES = new Map<string, string>([
  // ── PRIORIDAD (2026-07-30) ──────────────────────────────────────────────────
  // `getBrandKey` (backfill/scraper) prueba este Map ENTERO antes que
  // KNOWN_BRAND_PHRASES, y dentro de cada lista gana la PRIMERA entrada que
  // calce. O sea: la prioridad de marca es el ORDEN, no la logica. Estas
  // entradas existen para que una marca especifica le gane a una regla mas
  // golosa que la tapaba; varias ya estan en KNOWN_BRAND_PHRASES y se repiten
  // aqui a proposito, solo para adelantarlas.
  //
  // Medido el 30 jul 2026 sobre las 76 ofertas cuyo brandKey contradecia al de
  // su producto. NO se pueden arreglar "a mano" en la BD: `brand:backfill`
  // re-deriva el brandKey del titulo en cada corrida y pisaria la correccion.
  //
  // El ORDEN DE ESTE BLOQUE IMPORTA: "khemo" va antes que "lion rolling circus"
  // porque Kushbreak titula "Bandeja metalica Khemo Papers" pero su URL y su
  // campo `brand` dicen Lion Rolling Circus, y el titulo es la fuente buena.
  ["re stash", "re-stash"],            // "BongLab Contenedor Re:Stash" -> le ganaba bonglab (30 ofertas)
  ["khemo", "khemo"],                  // URL/brand de Kushbreak mal puestos -> le ganaba lion-rolling-circus
  ["ispire", "ispire"],                // "DynaVap Ispire The Wand" -> le ganaba dynavap
  ["zippo", "zippo"],                  // "Encendedor Zippo Santa Cruz" -> le ganaba el alias santa cruz (regresion de r61)
  ["clipper", "clipper"],              // "Encendedor Clipper Metalico Volcano" -> le ganaba el alias volcano
  ["lion rolling circus", "lion-rolling-circus"], // -> le ganaba el alias papelillo celulosa transparente
  ["bongalab", "bonglab"],             // typo de GrowBarato; sin esto cae al fallback gb-the-green-brand
  // r68 (2026-07-30). Los dos casos siguientes NO venian del fallback por
  // description sino del campo `brand` que declara la propia tienda, que en
  // Friendly Grow es poco fiable: declara GALAXY en un Dazzleaf y PHOENIX STAR
  // en una ficha cuyo titulo lleva otra marca entre comillas. Como ese campo
  // alimenta el mismo string que el titulo, la unica palanca es el orden.
  ["phoenix star", "phoenix-star"],    // 'Bong ... Phoenix "AKU Tribal"' -> le ganaba "aku", que esta en la posicion 1
  ["dazzleaf", "dazzleaf"],            // "Dazzleaf Spaceman" con brand=GALAXY -> le ganaba galaxy
  // r69: mismo patron, ahora en Kushbreak. Declara brand="GRAV®" en 5 ofertas
  // cuyo titulo Y url dicen MJ Arsenal, y "grav" le ganaba por orden. Escondia
  // 5 ofertas de una marca con 62 ofertas en el catalogo y ningun producto.
  ["mj arsenal", "mj-arsenal"],
  // r74 (2026-07-30, 5a sesion): EL MISMO PATRON PERO AL REVES -- aca la fuente
  // que miente es la URL, y el campo `brand` de la tienda es el que acierta.
  // Fumetas publica el Integra Boost 320g bajo la URL
  // "fumetas.cl/boveda-size-320g-55": le dejo el slug de la marca COMPETIDORA.
  // El titulo dice "Integra Boost" y el campo brand tambien, pero "boveda" esta
  // antes que "integra boost" en KNOWN_BRAND_PHRASES y gana por orden.
  // Lo encontro el mapa de marcas y de paso lo ensuciaba: boveda figuraba con 6
  // huerfanas en 3 tiendas cuando en realidad solo tiene 2 ofertas reales.
  ["integra boost", "integra-boost"],
  // ────────────────────────────────────────────────────────────────────────────
  ["the bulldog amsterdam", "the-bulldog"],
  ["the bulldog", "the-bulldog"],
  ["bulldog", "the-bulldog"],
  ["calvo glass", "calvo"],
  ["bong lab", "bonglab"],
  ["piece maker", "piecemaker"],
  ["pmg", "piecemaker"],
  ["easy valve", "storz-bickel"],
  ["solid valve", "storz-bickel"],
  ["volcano", "storz-bickel"],
  ["mighty", "storz-bickel"],
  ["crafty", "storz-bickel"],
  ["lightning grinder", "galaxy"],
  ["papelillo celulosa transparente", "c-thru"],
  // Huecos de alias: la misma marca escrita distinto segun la tienda. Sin estas
  // entradas, KNOWN_BRAND_PHRASES resuelve cada forma a su propio brandKey y toda
  // herramienta que agrupe por marca queda ciega al cruce (medido el 29 jul 2026:
  // 0 productos con brandKey=airis contra 8 con airistech). El canonico es el que
  // ya usan los Product existentes, porque Product.brandKey es URL publica.
  ["airis", "airistech"],
  ["da vinci", "davinci"],
  ["santa cruz", "santa-cruz-shredder"],
]);

export const KNOWN_BRANDS = [
  "raw",
  "ocb",
  "bonglab",
  "galaxy",
  "gizeh",
  "zippo",
  "calvo",
  "clipper",
  "pax",
  "ozeta",
  "futurola",
  "blazy susan",
  "storz bickel",
  "storz & bickel",
  "dynavap",
  "davinci",
  "slx",
  "hemper",
  "the bulldog",
  "cabo",
  "piecemaker",
  "american helix",
  "top smoke",
  "zengaz",
  "blunt wrap",
  "kush hemp",
  "formula secreta",
  "focus v",
  "lion rolling circus",
  "airis",
  "mr pipe cleaner",
  "vibes",
  "kush",
  "aku",
  "bukket",
  "c-thru",
  "cookies",
  "dark horse",
  "honeypuff",
  "kema",
  "special blue",
  "syfy",
  "waxmaid",
  "weecke",
  "yocan",
];

export const MATERIAL_TOKENS = new Set([
  "acrilico",
  "aluminio",
  "aluminum",
  "borosilicato",
  "borosilicate",
  "ceramic",
  "ceramics",
  "ceramica",
  "ceramico",
  "carton",
  "cartonico",
  "cardboard",
  "carbon",
  "cuarzo",
  "glass",
  "madera",
  "metal",
  "metalica",
  "metalico",
  "plastic",
  "plastico",
  "pyrex",
  "quartz",
  "silicona",
  "silicone",
  "vidrio",
]);

export const MATERIAL_KEYS = new Map([
  ["aluminio", "metal"],
  ["aluminum", "metal"],
  ["borosilicato", "glass"],
  ["borosilicate", "glass"],
  ["ceramic", "ceramic"],
  ["ceramics", "ceramic"],
  ["ceramica", "ceramic"],
  ["ceramico", "ceramic"],
  ["carton", "paper"],
  ["cartonico", "paper"],
  ["cardboard", "paper"],
  ["carbon", "carbon"],
  ["cuarzo", "quartz"],
  ["metalica", "metal"],
  ["metalico", "metal"],
  ["pyrex", "glass"],
  ["quartz", "quartz"],
  ["silicona", "silicone"],
  ["silicone", "silicone"],
  ["vidrio", "glass"],
  ["plastic", "plastic"],
  ["plastico", "plastic"],
]);

export const DESCRIPTOR_TOKENS = new Set([
  "amarillo",
  "azul",
  "black",
  "blanco",
  "blue",
  "classic",
  "clasica",
  "clasico",
  "clear",
  "dorado",
  "grande",
  "green",
  "mediana",
  "mediano",
  "mini",
  "negra",
  "negro",
  "pequena",
  "pequeno",
  "red",
  "rojo",
  "transparente",
  "verde",
  "white",
]);

export const DESCRIPTOR_KEYS = new Map([
  ["black", "black"],
  ["negra", "black"],
  ["negro", "black"],
  ["blue", "blue"],
  ["azul", "blue"],
  ["clear", "clear"],
  ["transparente", "clear"],
  ["green", "green"],
  ["verde", "green"],
  ["red", "red"],
  ["rojo", "red"],
  ["white", "white"],
  ["blanco", "white"],
  ["clasica", "classic"],
  ["clasico", "classic"],
  ["mediano", "mediana"],
  ["pequena", "mini"],
  ["pequeno", "mini"],
]);

export const COLOR_GROUPS = [
  ["amarillo"],
  ["azul", "blue", "celeste"],
  ["black", "negra", "negro"],
  ["blanco", "white"],
  ["clear", "transparente"],
  ["dorado", "gold"],
  ["green", "verde"],
  ["morado", "purple"],
  ["pink", "rosada", "rosado", "rose"],
  ["plateado", "silver"],
  ["red", "rojo"],
];

export const COLOR_KEYS = new Map<string, string>(
  COLOR_GROUPS.flatMap((group) => group.map((token) => [token, group[0]] as const)),
);

export const SCALE_GROUPS = [
  ["mini", "pequena", "pequeno", "small"],
  ["mediana", "mediano", "medium"],
  ["grande", "large"],
];

export const SCALE_KEYS = new Map<string, string>(
  SCALE_GROUPS.flatMap((group) => group.map((token) => [token, group[0]] as const)),
);

export const HARD_MODEL_TOKENS = new Set([
  "diamond",
  "giratorio",
  "herb",
  "lightning",
  "lite",
  "mars",
  "model",
  "pocket",
  "pro",
  "quartz",
  "saver",
  "square",
  "swing",
]);

export const BRAND_SIZE_MATCH_CATEGORIES = new Set([
  "accesorios de extraccion",
  "conos y blunts",
  "contenedores y estuches",
  "encendedores y sopletes",
  "filtros y boquillas",
  "limpieza",
  "papelillos",
  "repuestos para bongs y vaporizadores",
]);

export const BRAND_MODEL_MATCH_CATEGORIES = new Set([
  "accesorios de extraccion",
  "bandejas y ceniceros",
  "bongs",
  "contenedores y estuches",
  "encendedores y sopletes",
  "filtros y boquillas",
  "limpieza",
  "moledores",
  "papelillos",
  "pipas",
  "repuestos para bongs y vaporizadores",
  "vaporizadores herbales",
]);

// Frases de sabor (incluye multi-palabra y español) para nombrar variantes en la UI.
export const FLAVOR_KEYWORDS = [
  "banana",
  "cherry",
  "coconut",
  "chocolate",
  "blueberry",
  "bubble gum",
  "bubblegum",
  "grape",
  "minty",
  "mint",
  "vainilla",
  "vanilla",
  "strawberry",
  "frutilla",
  "cereza",
  "coco",
  "platano",
  "uva",
  "menta",
];

// Tokens individuales de sabor/marcador de sabor que usa el matcher (getPaperVariant, MODEL_TOKENS).
export const FLAVOR_TOKENS = new Set([
  "flavour",
  "flavours",
  "sabor",
  "sabores",
  "flavored",
  "banana",
  "cherry",
  "coconut",
  "chocolate",
  "blueberry",
  "bubble",
  "grape",
  "minty",
  "vainilla",
  "strawberry",
]);

export const GENERIC_TOKENS = new Set([
  "a",
  "accesorio",
  "accesorios",
  "aleatoria",
  "aleatorio",
  "aprox",
  "aproximado",
  "articulo",
  "articulos",
  "activado",
  "activo",
  "bandeja",
  "bandejas",
  "basic",
  "bong",
  "bongs",
  "boquilla",
  "boquillas",
  "brand",
  "blanqueado",
  "blanqueados",
  "blanquear",
  "blanqueamiento",
  "cachimba",
  "cachimbas",
  "cannabis",
  "cenicero",
  "ceniceros",
  "chile",
  "cl",
  "cierre",
  "cm",
  "color",
  "colorante",
  "colorantes",
  "colores",
  "compacto",
  "compartidor",
  "compartimento",
  "compartimentos",
  "con",
  "de",
  "del",
  "duradero",
  "diseno",
  "el",
  "eleccion",
  "en",
  "encendedor",
  "encendedores",
  "enrolar",
  "extra",
  "extrafino",
  "extrafinos",
  "fine",
  "fino",
  "finos",
  "fumar",
  "fumador",
  "fumadores",
  "filtro",
  "filtros",
  "friendly",
  "friendlygrow",
  "generico",
  "gb",
  "green",
  "grinder",
  "growbarato",
  "hoja",
  "hojas",
  "html",
  "http",
  "https",
  "king",
  "kit",
  "kushbreak",
  "la",
  "las",
  "liar",
  "los",
  "m",
  "marihuana",
  "metalico",
  "metalica",
  "modelo",
  "ml",
  "mm",
  "moledor",
  "moledores",
  "natural",
  "neodimio",
  "origen",
  "pack",
  "para",
  "parafernalia",
  "papel",
  "papeleria",
  "papeles",
  "papelillo",
  "papelillos",
  "parte",
  "partes",
  "pipa",
  "pipas",
  "pieza",
  "piezas",
  "piso",
  "pisos",
  "piranha",
  "producto",
  "productos",
  "raw",
  "recargable",
  "resistente",
  "set",
  "shop",
  "sin",
  "size",
  "slim",
  "smokeshop",
  "soplete",
  "sopletes",
  "starter",
  "the",
  "tienda",
  "tamiz",
  "tip",
  "tips",
  "tray",
  "ultra",
  "ultrafino",
  "ultrafinos",
  "u",
  "ud",
  "uds",
  "und",
  "unidad",
  "unidades",
  "usar",
  "uso",
  "variado",
  "variados",
  "variedad",
  "variedades",
  "vaporizador",
  "vaporizadores",
  "vegano",
  "www",
  "y",
]);

export const MODEL_TOKENS = new Set([
  "45",
  "90",
  "artesano",
  "automatico",
  "bamboo",
  "beaker",
  "brazilian",
  "bucket",
  "classic",
  "clasica",
  "clasico",
  "coil",
  "crafty",
  "diamond",
  "emerald",
  "flight",
  "flat",
  "full",
  "girl",
  "honeycomb",
  "inline",
  "king-size",
  "macho",
  "mighty",
  "organic",
  "percolator",
  "prepare",
  "pro",
  "regular",
  "rig",
  "slurper",
  "straight",
  "tube",
  "venty",
  "weld",
  "herb",
  "saver",
  "mini",
  "mars",
  "swing",
  "lite",
  "ecologico",
  "eco",
  "tarjeta",
  "card",
  "acrilico",
  "acrylic",
  "llavero",
  "keychain",
  "ceramics",
  "quartz",
  "lightning",
]);

export const KNOWN_MODEL_PHRASES = [
  "baby cake",
  "beaker plus",
  "beaker tree perc",
  "big blow",
  "big eye",
  "bongbastic",
  "bubbler kush",
  "color cube",
  "classic ice",
  "cristal mini",
  "diamond",
  "doble cuerno",
  "doble inline",
  "dream rig",
  "fat candy",
  "glycerin green avalanche",
  "glycerin thicc",
  "glycerin the yeti",
  "handy rig",
  "headshot",
  "heavy bubbler",
  "heavy trash",
  "honey drips",
  "honey waffle",
  "jelly drop",
  "jelly fish",
  "k104 moon",
  "k276",
  "k306",
  "k41",
  "k47 medusa",
  "k99 octopus",
  "km3 clear",
  "km8 viper",
  "little buchner",
  "mad professor",
  "mercurial kh1",
  "mercurial smokey",
  "mini beaker",
  "nevis rig",
  "new pro",
  "pocket bell",
  "prisma",
  "pro model",
  "r2 bonglab",
  "r3 mini",
  "rick sanchez",
  "roller coaster",
  "shiva blue",
  "space oddity",
  "space opera",
  "straight tube",
  "the sheikh",
  "the trash",
  "tiny bell",
  "unikorn",
  "water splash",
];

export const EXCLUSIVE_MODEL_GROUPS = [
  ["45", "90"],
  ["brazilian", "girl", "classic", "emerald", "prepare"],
  ["bucket", "slurper", "honeycomb", "flat", "regular"],
  ["crafty", "mighty", "venty"],
];

export const EXCLUSIVE_OPTION_TOKENS = new Set([
  "boquilla",
  "boquillas",
  "filtro",
  "filtros",
  "insert",
  "kit",
  "king-size",
  "pre-rolled",
  "pre-rolado",
  "pre-rolados",
  "roll",
  "rollo",
  "sabanas",
  "slim",
  "tip",
  "tips",
]);

export const DESCRIPTOR_WILDCARD_TOKENS = new Set(["color", "colores"]);

export const OPTIONAL_DESCRIPTOR_TOKENS = new Set([
  "amarillo",
  "animal",
  "azul",
  "black",
  "blanco",
  "blue",
  "celeste",
  "clear",
  "color",
  "colores",
  "dorado",
  "gold",
  "green",
  "morado",
  "natural",
  "negra",
  "negro",
  "pink",
  "plateado",
  "print",
  "purple",
  "red",
  "rojo",
  "rose",
  "silver",
  "transparente",
  "verde",
  "white",
]);

export const EXCLUSIVE_DESCRIPTOR_GROUPS = [
  ["amarillo"],
  ["animal"],
  ["azul", "blue", "celeste"],
  ["black", "negra", "negro"],
  ["blanco", "white"],
  ["clear", "transparente"],
  ["dorado", "gold"],
  ["green", "verde"],
  ["morado", "purple"],
  ["pink", "rose"],
  ["plateado", "silver"],
  ["print"],
  ["red", "rojo"],
];

export const EXCLUSIVE_DESCRIPTOR_KEYS = new Map<string, string>(
  EXCLUSIVE_DESCRIPTOR_GROUPS.flatMap((group) => group.map((token) => [token, group[0]] as const)),
);
